### ISSUE TITLE
Exporting the template to Overleaf gallery

### ISSUE THREAD

**Issue by nsapoval** [khyox/GR#2]
I have managed to slightly modify your template to work well with Overleaf. I think multiple people might benefit from exporting this template to the Overleaf template gallery. If you agree we can review the Overleaf template document and subsequently share it.

**Comment by khyox** [comment]
Sounds good, Nicolae! Do you want to do a PR for this so that I can test it on Overleaf? Just let me know how you want to proceed. Thanks!

**Comment by martinknytl** [comment]
Hi,
Can I find Genome Research template in Overleaf templat galllery? If yes, under what title? This GitHub GR example does not work to me in Overleaf.

**Comment by khyox** [comment]
Hi @martinknytl, perhaps @nsapoval can help you with that.

**Comment by lzhengcao** [comment]
> I have managed to slightly modify your template to work well with Overleaf. I think multiple people might benefit from exporting this template to the Overleaf template gallery. If you agree we can review the Overleaf template document and subsequently share it.

hi nsaponal, could you share your GR template of Overleaf version with me? thanks a lot

**Comment by khyox** [comment]
Closing as no PR has been issued to address this.
