### ISSUE TITLE
Possible .docx template?

### ISSUE THREAD

**Issue by frankchen121212** [khyox/GR#3]
Hello, thank you for the nice template.

Do you have the word template (possibly a .docx file ) for submission to Genome Research? I couldn't find one on the official website.

Thank you!

**Comment by khyox** [comment]
Hi. No, I am sorry, I don't have a template for MS Word. In fact, I prepared this LaTeX template so that I was able to avoid using a proprietary software like MS Word and instead use an open source alternative widely used in engineering and quantitative sciences. :)
